# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d3170b2fb29ad3d70b76fababd64560e335785a00b7f2bac546f7adf380b0dd2c4abdfc3c40e27e29771ffbb826fdc91ddabf45e5ab725b8bd05ef32fbd7862

test:
  secret_key_base: 2da64abab6477693df6556a7b69e118f454a3fab50869d592269c01712d6b59aa5f7589db1d3dc8413939e913d23c44c9c0730ba6eae76f4c7556decc0f17f31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
